### PR TITLE
Nix Flake

### PR DESCRIPTION
**Pull request by KamWithK**
Flake for Nix/NixOS users

Both includes a dev environment and packaged libninja

### CODE REVIEW

**Comment by kurtbuilds** [comment]
Can you add a section to the readme on how to use it? I don't use nix so not sure exactly what this does.

**Comment by KamWithK** [comment]
> Can you add a section to the readme on how to use it? I don't use nix so not sure exactly what this does.

Yeah sure I will soon

TLDR though Nix does stuff its own way so to be able to use anything you gotta repackage specifically for Nix, the flake in this PR packages libninja and also provides a dev environment with basic Rust stuff you can use

**Comment by KamWithK** [comment]
> Can you add a section to the readme on how to use it? I don't use nix so not sure exactly what this does.

Added to the docs how to run libninja with Nix run, the command will start working after this gets merged (because it refers to the flake as `kurtbuilds/libninja`)

Feel free to ask me any questions about it

**Comment by kurtbuilds** [comment]
Works for me! Thank you for adding this.

**Comment by KamWithK** [comment]
Thanks for merging!

**Pull request merged**
